DEBUG 2020-10-28 11:09:59.117 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-28 11:09:59.118 UTC: 	 Running on: Linux lxplus737.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-28 11:09:59.118 UTC: 	 Executing command: 'status'
DEBUG 2020-10-28 11:09:59.119 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
ERROR 2020-10-28 11:09:59.120 UTC: 	 Error: crab_submit_DYm50_MiniToNano.py is not a valid CRAB project directory.
ERROR 2020-10-28 11:09:59.120 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 623, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_submit_DYm50_MiniToNano.py is not a valid CRAB project directory.
INFO 2020-10-28 11:09:59.145 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab.log
DEBUG 2020-10-28 11:38:32.039 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-28 11:38:32.040 UTC: 	 Running on: Linux lxplus737.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-28 11:38:32.040 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-28 11:38:32.042 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
INFO 2020-10-28 11:38:32.045 UTC: 	 Will use CRAB configuration file crab_submit_DYm50_MiniToNano.py
DEBUG 2020-10-28 11:38:32.045 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-28 11:38:32.071 UTC: 	 Working area '/eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab_projects/crab_DYJetsToLL_mg271_amcatnlo-pythia8_test_NanoAOD' already exists 
Please change the requestName in the config file
ERROR 2020-10-28 11:38:32.071 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab_projects/crab_DYJetsToLL_mg271_amcatnlo-pythia8_test_NanoAOD' already exists 
Please change the requestName in the config file
INFO 2020-10-28 11:38:32.089 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab.log
DEBUG 2020-10-28 11:46:57.939 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-28 11:46:57.939 UTC: 	 Running on: Linux lxplus737.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-28 11:46:57.939 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-28 11:46:57.940 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
INFO 2020-10-28 11:46:57.944 UTC: 	 Will use CRAB configuration file crab_submit_DYm50_MiniToNano.py
DEBUG 2020-10-28 11:46:57.944 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-28 11:46:57.971 UTC: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 5000 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-10-28 11:46:57.972 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 5000 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-10-28 11:46:57.977 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab.log
DEBUG 2020-10-28 11:48:08.601 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-28 11:48:08.602 UTC: 	 Running on: Linux lxplus737.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-28 11:48:08.602 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-28 11:48:08.609 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
INFO 2020-10-28 11:48:08.626 UTC: 	 Will use CRAB configuration file crab_submit_DYm50_MiniToNano.py
DEBUG 2020-10-28 11:48:08.627 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-10-28 11:48:08.676 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-10-28 11:48:08.677 UTC: 	 Working area '/eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab_projects/crab_DYJetsToLL_mg271_amcatnlo-pythia8_test_NanoAOD' already exists 
Please change the requestName in the config file
ERROR 2020-10-28 11:48:08.677 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab_projects/crab_DYJetsToLL_mg271_amcatnlo-pythia8_test_NanoAOD' already exists 
Please change the requestName in the config file
INFO 2020-10-28 11:48:08.689 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab.log
DEBUG 2020-10-28 12:33:24.626 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-28 12:33:24.627 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-28 12:33:24.627 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-28 12:33:24.627 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
INFO 2020-10-28 12:33:24.628 UTC: 	 Will use CRAB configuration file crab_submit_DYm50_MiniToNano.py
DEBUG 2020-10-28 12:33:24.628 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-28 12:33:24.659 UTC: 	 Invalid CRAB configuration: Parameter Data.inpuDBS is not known. Maybe you mean Data.inputDBS?
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-10-28 12:33:24.659 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.inpuDBS is not known. Maybe you mean Data.inputDBS?
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-10-28 12:33:24.665 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab.log
DEBUG 2020-10-28 12:34:05.690 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-28 12:34:05.691 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-28 12:34:05.691 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-28 12:34:05.691 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
INFO 2020-10-28 12:34:05.692 UTC: 	 Will use CRAB configuration file crab_submit_DYm50_MiniToNano.py
DEBUG 2020-10-28 12:34:05.692 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-10-28 12:34:05.694 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-10-28 12:34:05.695 UTC: 	 Working area '/eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab_projects/crab_DYJetsToLL_official_MiniAOD_to_NanoAOD' already exists 
Please change the requestName in the config file
ERROR 2020-10-28 12:34:05.695 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab_projects/crab_DYJetsToLL_official_MiniAOD_to_NanoAOD' already exists 
Please change the requestName in the config file
INFO 2020-10-28 12:34:05.701 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab.log
DEBUG 2020-10-28 13:53:56.336 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-28 13:53:56.337 UTC: 	 Running on: Linux lxplus710.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-28 13:53:56.337 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-28 13:53:56.338 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
INFO 2020-10-28 13:53:56.339 UTC: 	 Will use CRAB configuration file crab_submit_DYm50_MiniToNano.py
DEBUG 2020-10-28 13:53:56.339 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-28 13:53:56.397 UTC: 	 Invalid CRAB configuration: Parameter Data.unitsPerJob is mandatory for 'FileBased' splitting mode.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-10-28 13:53:56.397 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.unitsPerJob is mandatory for 'FileBased' splitting mode.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-10-28 13:53:56.404 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DYm50_MiniToNano/crab.log
